# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: cache

    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public"
                bundle_resources:
                    enabled: true

    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction

    filter_sets:
        cache: ~

        # the name of the "filter set"
        vignettes_projets:

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 290x180 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [290, 180], mode: outbound }

        vignettes_services:

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 540x340 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [540, 340], mode: outbound }

        images_projets:
        
            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 1045x605 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [1045, 605], mode: outbound }

        profil:
        
            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 400x400 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [400, 400], mode: outbound }
        
        images_services:
        
            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 1920x400 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [1920, 400], mode: outbound }

        images_slider:
        
            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 1920x1080 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [1920, 1080], mode: outbound }

        logo_partenaire:
        
            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 400x140 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [400, 140], mode: outbound }
